### ISSUE TITLE
PayloadTooLargeError when generating HTML

### ISSUE THREAD

**Issue by vcampitelli** [EDMdesigner/editor-issues#64]
Hi there!

I'm having the following problem with the _project/generate_ endpoint.

```
PayloadTooLargeError: too many parameters
   at queryparse (/home/ubuntu/deployments/2016-10-24_11-29-21/eml-generator-service/node_modules/body-parser/lib/types/urlencoded.js:144:13)
   at parse (/home/ubuntu/deployments/2016-10-24_11-29-21/eml-generator-service/node_modules/body-parser/lib/types/urlencoded.js:75:9)
   at /home/ubuntu/deployments/2016-10-24_11-29-21/eml-generator-service/node_modules/body-parser/lib/read.js:108:18
   at invokeCallback (/home/ubuntu/deployments/2016-10-24_11-29-21/eml-generator-service/node_modules/body-parser/node_modules/raw-body/index.js:262:16)
   at done (/home/ubuntu/deployments/2016-10-24_11-29-21/eml-generator-service/node_modules/body-parser/node_modules/raw-body/index.js:251:7)
   at IncomingMessage.onEnd (/home/ubuntu/deployments/2016-10-24_11-29-21/eml-generator-service/node_modules/body-parser/node_modules/raw-body/index.js:307:7)
   at emitNone (events.js:67:13)
   at IncomingMessage.emit (events.js:166:7)
   at IncomingMessage.wrapped (/home/ubuntu/deployments/2016-10-24_11-29-21/eml-generator-service/node_modules/newrelic/lib/transaction/tracer/index.js:183:28)
   at IncomingMessage.wrappedEmit [as emit] (/home/ubuntu/deployments/2016-10-24_11-29-21/eml-generator-service/node_modules/newrelic/lib/transaction/tracer/index.js:220:46)
```

Some information:
_Instance: API_MEDIAPOST
User: maxpress
Project ID: 58232997b80001015f9819a0_

Can you help me? :smile:

**Comment by gyulanemeth** [comment]
Hello,

I guess it's a huge template... I can also see that you send the body of the request urlencoded. Can you try to send it as application/json?

**Comment by vcampitelli** [comment]
Yeah, It's kind of huge :flushed:

I can, but the _project/generate_ endpoint is a simple GET request without body, right?

Att.,

**Comment by iamgaborgithub** [comment]
Dear Vinícius,

I’m Gábor from edmdesigner.com. I organize our public Github issues and close this ticket because it looks outdated. If you do not agree with it please leave a comment and I’ll be in touch.

If you have any new issues or feedback to share then please don’t hesitate and open a new ticket or send us an email to support@edmdesigner.com.

I hope you are well.

Best regards,
Gábor Kovács
Project Manager @ edmdesigner.com
